Module6 task2
htmlacademy-ecmascript/1340827-big-trip-12 pull request #10
Opened 2020-09-01 23:56 UTC by Starinets

2020-09-02 03:25 UTC, AlexMasterov requested changes

2020-09-02 03:25 UTC, AlexMasterov commented on src/view/point-edit.js
<details>
<summary>view/point-edit.js</summary>

https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/blob/caefa3da20abf837ab6e2ab787ec85e2df9cbe23/src/view/point-edit.js#L305
</details>

```js
evt.target.valueAsNumber // NaN
```

См. внимательно [diff с исправлением **разметки** из прошлого ревью](https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/pull/9#discussion_r479870033).

2020-09-02 03:25 UTC, AlexMasterov commented on src/view/point-edit.js
>  export default class PointEdit extends SmartView {
Компонент протекает.

Б36

После удаления элемента компонента нужно также удалить экземпляры `flatpickr`.

См. [пример удаления в демо проекте](https://github.com/htmlacademy-ecmascript/taskmanager-12/blob/module-9/src/view/task-edit.js#L178-L187).

2020-09-02 03:25 UTC, AlexMasterov commented on src/view/point-edit.js
> +    if (this._startDatePicker) {
https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/blob/caefa3da20abf837ab6e2ab787ec85e2df9cbe23/src/view/point-edit.js#L191

```diff
- if (this._startDatePicker) {
+ if (this._startDatePicker === null) {
```

2020-09-02 03:25 UTC, AlexMasterov commented on src/view/point-edit.js
>    restoreHandlers() {
После добавления точки маршрута в избранное перестает работать `flatpickr`.

Нужно разобраться и исправить.

2020-09-02 03:25 UTC, AlexMasterov commented on src/view/point-edit.js
> +  _startDateChangeHandler([userDate]) {
После изменение начальной даты нужно перерисовать список дней.

2020-09-02 03:25 UTC, AlexMasterov commented on src/main.js
<details>
<summary>utils/general.js</summary>

https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/blob/caefa3da20abf837ab6e2ab787ec85e2df9cbe23/src/utils/general.js#L2-L4
</details>

Нужно удалить.

2020-09-02 03:28 UTC, AlexMasterov commented
Обрати внимание не доп. критерии:

[`Д 3`](https://up.htmlacademy.ru/ecmascript/12/criteries#d3)
> Название методов и свойств объектов не содержит название объектов

[`Д 8`](https://up.htmlacademy.ru/ecmascript/12/criteries#d8)
> Методы внутри классов упорядочены

2020-09-02 16:00 UTC, Starinets commented on src/main.js
> +  } else {
начальная и конечная дата маршрута могут находиться в разных месяцах или в одном месяце но в разных днях. Д12 говорит о том, что если условие истино в любом случае, то else опускается. В данном случае длительность может быть как один день, так и несколько дней в одном месяце или покрывать несколько месяцев.

2020-09-02 16:32 UTC, Starinets commented on src/view/point-edit.js
> +    if (this._startDatePicker) {
!== ?

2020-09-02 16:35 UTC, Starinets commented on src/view/point-edit.js
> +  _startDateChangeHandler([userDate]) {
Сделаю вместе с моделью

2020-09-03 03:19 UTC, AlexMasterov requested changes

2020-09-03 03:22 UTC, AlexMasterov commented on src/main.js
> +  } else {
> начальная и конечная дата маршрута могут находиться в разных месяцах или в одном месяце <...>

См. [Date.p.`getMonth`](https://beta.developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth):
> Значение, возвращённое методом, является **целым числом** от `0` до `11`

Твое условие проверяет, что начальная и конечная дата маршрута не находятся в одном календарном (числовом) месяце: (важно знать и помнить)
```js
const isNotSameDateMonth = (dateA, dateB) => dateA.getMonth() !== dateB.getMonth();

isNotSameDateMonth(new Date('2000-01-01'), new Date('2020-01-01')) // false
```

> В ТЗ пример формата даты для путешествий меньше года 😄

2020-09-03 03:44 UTC, AlexMasterov commented on src/view/point-edit.js
> +    if (this._startDatePicker) {
> !== ?

![type1](https://i.imgur.com/Uv9Q2KO.jpg)
![type2](https://i.imgur.com/jQeuTjm.png)

2020-09-03 14:02 UTC, merged

2020-09-03 14:04 UTC, Starinets commented on src/view/point-edit.js
> +    if (this._startDatePicker) {
как объяснял Игорь на прошлых потоках - если понимать как происходит преобразование типов в сравнениях, то не так уж много и странного и магического остается в js