Module7 task1
htmlacademy-ecmascript/1340827-big-trip-12 pull request #11
Opened 2020-09-07 03:28 UTC by Starinets

2020-09-07 16:27 UTC, AlexMasterov requested changes

2020-09-07 16:27 UTC, AlexMasterov commented on src/constants.js
>  export {
<details>
<summary>constants.js</summary>

https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/blob/4e6c440b9206d18ac472d4b7983feadf2b0edac5/src/constants.js#L60
https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/blob/4e6c440b9206d18ac472d4b7983feadf2b0edac5/src/constants.js#L66-L76
</details>

Б14

2020-09-07 16:27 UTC, AlexMasterov commented on src/main.js
> +// render(filtersPlace, new FiltersView(FilterType.EVERYTHING), RenderPosition.BEFORE_END);
Б18

2020-09-07 16:27 UTC, AlexMasterov commented on src/main.js
> +infoPlace.querySelector(`.trip-main__event-add-btn`).addEventListener(`click`, (evt) => {
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/blob/4e6c440b9206d18ac472d4b7983feadf2b0edac5/src/main.js#L85
https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/blob/4e6c440b9206d18ac472d4b7983feadf2b0edac5/src/main.js#L104
</details>

Д26

Зачем создавали компонент 🤔

2020-09-07 16:27 UTC, AlexMasterov commented on src/presenter/point.js
> +        isMinorUpdate ? UpdateType.MINOR : UpdateType.PATCH,
<details>
<summary>_handlePointFormSubmit</summary>

https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/blob/4e6c440b9206d18ac472d4b7983feadf2b0edac5/src/presenter/point.js#L130
https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/blob/4e6c440b9206d18ac472d4b7983feadf2b0edac5/src/presenter/point.js#L134
</details>

Отрицание добавляет _сложности_ 🤔

```diff
- const isMinorUpdate = !isDatesEqual(this._point.startTime, editedPoint.startTime);
+ const isPatchUpdate = isDatesEqual(this._point.startTime, editedPoint.startTime);
```

```diff
- isMinorUpdate ? UpdateType.MINOR : UpdateType.PATCH,
+ isPatchUpdate ? UpdateType.PATCH : UpdateType.MINOR,
```

2020-09-07 16:27 UTC, AlexMasterov commented on src/presenter/trip.js
<details>
<summary>presenter/trip.js</summary>

https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/blob/4e6c440b9206d18ac472d4b7983feadf2b0edac5/src/presenter/trip.js#L57
https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/blob/4e6c440b9206d18ac472d4b7983feadf2b0edac5/src/presenter/trip.js#L222
https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/blob/4e6c440b9206d18ac472d4b7983feadf2b0edac5/src/presenter/trip.js#L60
</details>

Д18

2020-09-07 16:27 UTC, AlexMasterov commented on src/utils/filter.js
> +export const filter = {
<details>
<summary>filter</summary>

https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/blob/4e6c440b9206d18ac472d4b7983feadf2b0edac5/src/utils/filter.js#L3-L7
</details>

```diff
- export const filter = {
+ export const filterTypeToPoints = {
```

2020-09-07 16:32 UTC, AlexMasterov requested changes

2020-09-07 16:32 UTC, AlexMasterov commented on src/main.js
> +// import FiltersView from './view/filters';
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/blob/4e6c440b9206d18ac472d4b7983feadf2b0edac5/src/main.js#L9
https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/blob/4e6c440b9206d18ac472d4b7983feadf2b0edac5/src/main.js#L16
</details>

Д18

2020-09-07 16:32 UTC, AlexMasterov commented on src/presenter/point.js
<details>
<summary>presenter/point.js</summary>

https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/blob/4e6c440b9206d18ac472d4b7983feadf2b0edac5/src/presenter/point.js#L74-L77
</details>

Б36

Если открыть форму редактирование точки и нажать на создание новой или применить сортировку, то обработчик на `Esc` не удаляется.

Нужно разобраться и исправить.

2020-09-07 16:49 UTC, Starinets commented on src/presenter/point-new.js
> +              id: getNewID()
но на 7.1 сервера нет, а данные в модели сохранить надо

2020-09-08 13:57 UTC, Starinets commented on src/presenter/point.js
Подскажи как это можно увидеть?

2020-09-08 14:34 UTC, AlexMasterov commented on src/presenter/point.js
> Подскажи как это можно увидеть?

<details>
<summary>DevTools</summary>

![image](https://user-images.githubusercontent.com/700213/92490200-6614a080-f1f9-11ea-8e54-517f3ad7bb3b.png)

</details>

2020-09-08 16:24 UTC, merged