Module7 task2
htmlacademy-ecmascript/1340827-big-trip-12 pull request #12
Opened 2020-09-13 17:37 UTC by Starinets

2020-09-13 23:01 UTC, AlexMasterov requested changes

2020-09-14 05:15 UTC, Starinets commented on src/view/statistics.js
> +    this._timeSpendChart = generateTimeSpendChart(timeSpendChart, this._points);
я не знаю как это сделать за меньшее количество циклов.

2020-09-14 05:24 UTC, Starinets commented on src/main.js
>  render(infoView, new MainInfoView(tripPath, tripDuration), RenderPosition.BEFORE_END);
По заданию они и не должны на сортировку и фильтры реагировать, только на изменение, удаление, добавление точек.

2020-09-14 06:09 UTC, Starinets commented on src/presenter/statistics.js
> +export default class Statistics {
в 7-2: Обратите внимание, фильтры на графики и диаграммы никак не влияют.

2020-09-14 06:58 UTC, AlexMasterov approved these changes
👍

2020-09-14 06:58 UTC, AlexMasterov commented on src/presenter/filter.js
> +      [FilterType.PAST]: filterTypeToPoints[FilterType.PAST](points, currentDate).length,
<details>
<summary>_getFilters</summary>

https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/blob/9777b5f8f6f69d285029f95873d3f01af461add4/src/presenter/filter.js#L56-L59
</details>

Б34~

Задача решается за один цикл и без создания трех временных массивов.

2020-09-14 06:58 UTC, AlexMasterov commented on src/view/statistics.js
> +const ChartOptions = {
ChartOption`s`

[`Б 7`](https://up.htmlacademy.ru/ecmascript/12/criteries#b7)
> Перечисления названы существительными в единственном числе

2020-09-14 06:58 UTC, AlexMasterov commented on src/view/statistics.js
> +const ChartSettingsToScales = {
Б3, ~Б7~

```diff
- const ChartSettingsToScales = {
+ const сhartScales = {
```
> Не забудь про Б14

2020-09-14 06:58 UTC, merged