Module8 task2
htmlacademy-ecmascript/1340827-big-trip-12 pull request #14
Opened 2020-09-19 18:43 UTC by Starinets

2020-09-20 05:05 UTC, AlexMasterov requested changes

2020-09-20 05:05 UTC, AlexMasterov commented on src/view/point-edit.js
> +
<details>
<summary>Ошибка при сохранение формы с пустым значением цены</summary>

```
The specified value "NaN" cannot be parsed, or is out of range.
```
```
api.js:83 PUT https://12.ecmascript.pages.academy/big-trip/points/0 400 (Bad Request)
```
</details>

<details>
<summary>Ошибка при создание точки с пустым значением цены</summary>

```
POST https://12.ecmascript.pages.academy/big-trip/points 400 (Bad Request)
```
</details>

Б2

2020-09-21 03:26 UTC, Starinets commented on src/presenter/point.js
> +    const resetFormState = () => {
но используется дважды, для презентера новой точки и для презентера точки. Поэтому отдельная функция.

2020-09-21 05:41 UTC, AlexMasterov commented on src/presenter/point.js
> +    const resetFormState = () => {
> но используется дважды

Даже если один один раз — это здесь не имеет значения.

Если `switch` не войдет в ветку `PointFormState.ABORTING`, то эта функция просто не будет использована (= _неиспользуемый код_).

2020-09-21 05:44 UTC, merged