Module6 task1
htmlacademy-ecmascript/1340827-big-trip-12 pull request #9
Opened 2020-08-30 18:42 UTC by Starinets

2020-08-31 03:38 UTC, AlexMasterov requested changes

2020-08-31 03:38 UTC, AlexMasterov commented on src/view/point-edit.js
> +          destinationPhotos,
<details>
<summary>view/point-edit.js</summary>

https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/blob/e485324fbb28b7659e3b6aee493e89df7fe65f5b/src/view/point-edit.js#L283-L287
https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/blob/e485324fbb28b7659e3b6aee493e89df7fe65f5b/src/view/point-edit.js#L295-L296
</details>

Нужно удалить.

<details>
<summary>mock/point.js</summary>

https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/blob/e485324fbb28b7659e3b6aee493e89df7fe65f5b/src/mock/point.js#L24
</details>

Для генерации структуры `destination` используй [`generateDestinationsInfo`](https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/blob/e485324fbb28b7659e3b6aee493e89df7fe65f5b/src/mock/destinations.js#L26):

```js
const destinations = generateDestinationsInfo();

// generatePoint
destinations: destinations[getRandomInteger(0, destinations.length - 1)],
```
Копировать по желанию.

<details>
<summary>view/point-edit.js</summary>

https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/blob/e485324fbb28b7659e3b6aee493e89df7fe65f5b/src/view/point-edit.js#L257-L261
</details>

Используй [`this._destinations`](https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/blob/e485324fbb28b7659e3b6aee493e89df7fe65f5b/src/view/point-edit.js#L193) чтобы проверить наличие доступности направления, и при наличие обнови (структуру) данных с описанием и фото.

> По итогу потребуется исключить возможность ввода недоступных направлений или указывать на это в форме, запрещая её сохранение

2020-08-31 03:38 UTC, AlexMasterov commented on src/view/point-edit.js
> +    delete data.destinationPhotos;
<details>
<summary>parseDataToPoint</summary>

https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/blob/e485324fbb28b7659e3b6aee493e89df7fe65f5b/src/view/point-edit.js#L302-L305
</details>

После всех исправлений постарайся не использовать оператор `delete` и не удалять/добавлять свойства постоянного объекта [`this_.data`](https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/blob/e485324fbb28b7659e3b6aee493e89df7fe65f5b/src/view/point-edit.js#L194).

2020-08-31 03:38 UTC, AlexMasterov commented on src/view/smart.js
> +    parent.replaceChild(newElement, prevElement);
<details>
<summary>updateElement</summary>

https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/blob/e485324fbb28b7659e3b6aee493e89df7fe65f5b/src/view/smart.js#L29
https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/blob/e485324fbb28b7659e3b6aee493e89df7fe65f5b/src/view/smart.js#L34
</details>

См. [ChildNode.`replaceWith`](https://beta.developer.mozilla.org/ru/docs/Web/API/ChildNode/replaceWith).

<details>
<summary>Реализация в Chromium</summary>

Этот метод сам проверяет наличие `ParentNode` (и выбрасывает исключение):

[third_party/blink/renderer/core/dom/`node.cc`](https://source.chromium.org/chromium/chromium/src/+/refs/tags/85.0.4183.40:third_party/blink/renderer/core/dom/node.cc;l=937-941;drc=c5f01d3e7fcd4d376f593120dd8010ac84155fae):
```cpp
void Node::ReplaceWith(const HeapVector<NodeOrStringOrTrustedScript>& nodes,
                       ExceptionState& exception_state) {
  Node* parent = parentNode();
  if (!parent)
    return;
````
```cpp
ContainerNode* Node::parentNode() const {
  return IsShadowRoot() ? nullptr : ParentOrShadowHostNode();
}
```
[third_party/blink/renderer/core/dom/`element.h`](https://source.chromium.org/chromium/chromium/src/+/refs/tags/85.0.4183.40:third_party/blink/renderer/core/dom/element.h;l=1239-1241):
```cpp
inline Element* Node::parentElement() const {
  return DynamicTo<Element>(parentNode());
}
```
</details>

2020-08-31 03:38 UTC, AlexMasterov commented on src/view/point-edit.js
> +      price: Number(evt.target.value),
https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/blob/e485324fbb28b7659e3b6aee493e89df7fe65f5b/src/view/point-edit.js#L161

```diff
- <input class="event__input  event__input--price" id="event-price-1" type="text" name="event-price" value="${data.price}"> 
+ <input class="event__input  event__input--price" id="event-price-1" type="number" name="event-price" value="${data.price}"> 
```

```diff
- price: Number(evt.target.value),
+ price: evt.target.valueAsNumber,
```

2020-08-31 03:38 UTC, AlexMasterov commented on src/view/point-edit.js
> +      isFavorite: !this._data.isFavorite
Добавление в избранное требуется обрабатывать сразу, т.е. без нажатия на кнопку `Save`: отправлять на сервер и при получение ответа изменять модель, перерисововать компонент.

Сейчас будет достаточно изменить данные в презентере.

2020-08-31 15:28 UTC, Starinets commented on src/utils/data.js
> +const updateItem = (items, update) => {
В параметрах передается ссылка на массив, в котором нужно обновить элемент и ссылка на сам элемент. Поэтому в данном случае updateItemById не подходит

2020-08-31 15:46 UTC, AlexMasterov commented on src/utils/data.js
> +const updateItem = (items, update) => {
> Поэтому в данном случае updateItemById не подходит

По названию `updateItemById` вполне можно понять, как происходит обновление. 
Название `updateItem` выглядит менее выразительным 😃

2020-08-31 16:24 UTC, Starinets commented on src/view/point-edit.js
> +    delete data.destinationPhotos;
Я тогда не понимаю вообще смысла в использовании parseDataToPoint/parsePointToData если это не способ подготовить данные для удобного использования компонентом при отрисовке, дополнить "виртуальными" данными, для того, чтоб не проверять при отрисовке. А при передаче наверх измененных данных удаляем все данные не относящиеся непосредственно к точке маршрута. В чем тогда смысл this._data?

2020-08-31 16:25 UTC, Starinets commented on src/view/point-edit.js
> +    delete data.destinationPhotos;
Я тогда не понимаю вообще смысла в использовании parseDataToPoint/parsePointToData если это не способ подготовить данные для удобного использования компонентом при отрисовке, дополнить "виртуальными" данными, для того, чтоб не проверять при отрисовке. А при передаче наверх измененных данных удаляем все данные не относящиеся непосредственно к точке маршрута. В чем тогда смысл this._data?

2020-08-31 16:34 UTC, Starinets commented on src/presenter/trip.js
> +    this._unsortedPoints = updateItem(this._unsortedPoints, updatedPoint);
они там есть

2020-08-31 16:37 UTC, AlexMasterov commented on src/presenter/trip.js
> +    this._unsortedPoints = updateItem(this._unsortedPoints, updatedPoint);
https://github.com/htmlacademy-ecmascript/1340827-big-trip-12/blob/e485324fbb28b7659e3b6aee493e89df7fe65f5b/src/presenter/trip.js#L46

Почему они разделяют ссылку на один массив? 😄

На JS1 вроде тебе объяснял, что компилятор не "любит" двойное присвоение.

> Зато подобный прием часто используют в PHP

2020-08-31 18:44 UTC, Starinets commented on src/presenter/trip.js
> +    this._unsortedPoints = updateItem(this._unsortedPoints, updatedPoint);
Нет, точно не мне объяснял. Но если это плохо - переделаю.

2020-08-31 18:54 UTC, Starinets commented on src/view/point-edit.js
> +  destination: ``,
в структуре данных будут находится данные о точки назначения? И так будет приходить с сервера? Зачем? если есть отдельная структура destinations и связь между ними point.destination -> destinations[].name?

2020-09-01 05:33 UTC, AlexMasterov commented on src/view/point-edit.js
> +    delete data.destinationPhotos;
Мой комментарий не про решение, а про обновления объекта с помощью оператора `delete`. Нужно хорошо понимать последствия. Флаги меня не волнуют и их можешь вернуть 😃

Проблема в том, что мы до сих пор не можем пользоваться возможностями актуального стандарта:

<details>
<summary>Rest/Spread objects</summary>

```js
const parsePointToData = ({
  ...(point.destination && { offers: [] }),
  ...point,
}) => data
```
```js
const parseDataToPoint = ({ 
  needGenerateOffersTemplate, 
  needGeneratePhotosTemplate,
  ...data 
}) => point;
```
</details>

2020-09-01 09:11 UTC, AlexMasterov requested changes

2020-09-01 09:11 UTC, AlexMasterov commented on src/view/sort.js
> +  _onTypeChange(evt) {
Д4, Д6

2020-09-01 09:25 UTC, AlexMasterov commented on src/view/point-edit.js
> +  destination: ``,
> в структуре данных будут находится данные о точки назначения?

Да, см. [`ТЗ 1.9.1 Ресурсы`](https://up.htmlacademy.ru/ecmascript/12/project/big-trip#resource).

> И так будет приходить с сервера?

Да, уже.

> Зачем? если есть отдельная структура destinations и связь между ними point.destination -> destinations[].name?

`destinations` нужен для создания _новых_ точек маршрута, но как быть со старыми?

Представь, что пользователь в начале лета спланировал путешествие и создавал несколько точек маршрута, в которых выбрал доступное (на этот момент!) направление и доп. предложения. Потом началась пандемия и общий список направлений сократился, а (рыночные) цены на доп. предложения изменились. Откуда получить эти данные для старых точек маршрута?

Например, при редактировании созданной точки маршрута нужно использовать уже _выбранные_ `offers` из данных самой точки **и** _общие_ `offers[type]` из отдельной структуры. При этом предложения из общего списка не должны дублировать уже выбранные: по названию **и** цене. Могут быть предложения с одинаковым названием, но с разной (рыночной) ценой.

> Замечание про связь данных актуально для серверной разработки

2020-09-01 14:15 UTC, Starinets commented on src/presenter/point.js
> +    this._point = {};
mutable?

2020-09-01 14:32 UTC, Starinets commented on src/view/point-edit.js
> +  destination: ``,
ну возможно, чтоб не сильно загружать обучающихся, такое решение сойдет

2020-09-01 17:22 UTC, merged

2020-09-01 17:27 UTC, AlexMasterov commented on src/presenter/point.js
> +    this._point = {};
> mutable?

Извини, не понял вопроса.

> `null` = `no value (object)`

2020-09-01 17:31 UTC, AlexMasterov commented on src/view/point-edit.js
> +  constructor(point = createEmptyPoint(), destinations) {
Параметр по умолчанию задан первым: чтобы это сработало `createEmptyPoint()` нужно также забыть передать `destinations`. Желательно пересмотреть решение.

> Посмотрел после температуры 😃

2020-09-01 17:46 UTC, Starinets commented on src/view/point-edit.js
> +  constructor(point = createEmptyPoint(), destinations) {
Возможно тогда в теле конструктора проверять на undefined и тогда присваивать возврат функции генерирующей "шаблон" точки?

2020-09-01 17:54 UTC, AlexMasterov commented on src/view/point-edit.js
> +  constructor(point = createEmptyPoint(), destinations) {
Так уже работает.

Пока задай `destinations` параметр по умолчанию `[]`.